# Generated by Django 2.1.7 on 2019-02-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Contact_date',
            new_name='contact_date',
        ),
    ]
